name: Update Wrapper
on:
  push:
    branches: [ 'automatic-update' ]
  # schedule:
  #   # runs every day at 02:23 UTC
  #   - cron: '23 2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'
      - name: Get latest fixed open api definition
        id: latest-openapi
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'sonallux',
              repo: 'spotify-web-api',
            });
            const assetName = 'fixed-spotify-open-api.yml';
            const asset = response.data.assets.find(asset => asset.name === assetName);
            console.log(asset);
            const browserDownloadUrl = asset?.browser_download_url;
            console.log(browserDownloadUrl);
            if (!browserDownloadUrl) {
              console.log('Latest release did not contain the correct asset!');
              core.setFailed('Latest release did not contain the correct asset!');
            }
            return {release: response.data.name, browserDownloadUrl};
      - name: Check outputs
        run: 'echo "Latest release ${{ steps.latest-openapi.outputs.result.release }}: ${{ steps.latest-openapi.outputs.result.browserDownloadUrl }}"'
#      - name: Build tools
#        run: ./mvnw -B package -Pcli
#      - name: Download Spotify's OpenAPI
#        run: wget -O official-spotify-open-api.yml https://developer.spotify.com/_data/documentation/web-api/reference/open-api-schema.yml
#      - name: Patch Spotify's OpenAPI
#        run: ./scripts/patch-open-api.sh
#      - name: Create Pull Request
#        id: cpr
#        uses: peter-evans/create-pull-request@v3
#        with:
#          # Use a PAT so GitHub actions are triggered on the PR
#          token: ${{ secrets.GH_REPO_TOKEN }}
#          commit-message: "Automated update of Spotify's OpenAPI definition"
#          branch: 'spotify-openapi-update'
#          delete-branch: true
#          base: main
#          author: 'sonallux <13821543+sonallux@users.noreply.github.com>'
#          title: "Update of Spotify's OpenAPI definition"
#          body: |
#            Automated update of Spotify's OpenAPI definition
#
#            Generated by [this workflow run](https://github.com/sonallux/spotify-web-api/actions/runs/${{ github.run_id }}).
#      - name: Check outputs
#        run: 'echo "Pull Request ${{ steps.cpr.outputs.pull-request-operation }}: ${{ steps.cpr.outputs.pull-request-url }}"'
#      - name: Comment on PR
#        if: steps.cpr.outputs.pull-request-operation == 'created'
#        uses: actions/github-script@v3
#        with:
#          github-token: ${{secrets.GITHUB_TOKEN}}
#          script: |
#            github.issues.createComment({
#              issue_number: ${{ steps.cpr.outputs.pull-request-number }},
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: "@sonallux Spotify's OpenAPI definition has been updated!"
#            })
